source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'thin'
gem 'mongoid'
gem 'devise'

group :development do
  gem 'pry-rails'
  gem 'pry-remote'
  gem 'pry-debugger'
  gem 'coolline'
  gem 'awesome_print'
  gem 'better_errors'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'mongoid-rspec'
end
